name: Update Weather Cache

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 3  # Set a timeout to prevent long-running jobs
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone for faster checkout
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Cache pip dependencies
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp asyncio
      
      - name: Run weather cache update script
        run: python scripts/update_weather_cache.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update weather cache $(date +'%Y-%m-%d %H:%M:%S')" && git push)
